- id: '1578060156228'
  alias: '[System] New Repo In Hacs'
  description: ''
  trigger:
  - event_data:
      action: registration
    event_type: hacs/repository
    platform: event
  condition:
  - condition: template
    value_template: '"{{ trigger.event.data.repository is defined }}"'
  action:
  - data_template:
      message: '{% set repo = trigger.event.data.repository %} {% set id = trigger.event.data.repository_id
        %} [{{ repo }}](/hacs/repository/{{ id }}) was just added to HACS.'
      title: New repository in HACS
    service: persistent_notification.create
- id: '1578061745449'
  alias: '[System] Device Status'
  description: ''
  trigger:
  - entity_id:
    - sensor.system_asus_router
    - sensor.system_netgear_router
    - sensor.system_printer
    - sensor.system_nas
    - sensor.system_ir_blaster
    - sensor.system_ir_blaster_bedroom
    - sensor.system_ip_camera
    - sensor.system_xiaomi_gateway
    - sensor.system_milight_hub
    - sensor.system_axis_living_room
    - sensor.system_axis_passage
    - sensor.system_dafang
    - sensor.system_ip_camera
    for: 0:05:00
    platform: state
    to: Offline
  - entity_id: device_tracker.raspberrypi,device_tracker.raspberrypi_3,device_tracker.raspberrypi_2,device_tracker.meye_edfe3a04,device_tracker.raspberrypi_4,device_tracker.sannce_ip_camera,device_tracker.7811dc70faaf,device_tracker.78_11_dc_71_2d_18,device_tracker.axis_00408cd5badd,device_tracker.axis_00408cd5bad6,device_tracker.4c_11_bf_c5_a5_6e,device_tracker.broadlink_hallway,device_tracker.broadlink_bedroom,device_tracker.broadlink_rmminiccec6f,device_tracker.xiaomi_gateway,device_tracker.milight_controller,device_tracker.synology_nas,device_tracker.0023c116a0dd,device_tracker.rockrobo,device_tracker.78_11_dc_7b_b2_6a
    for: 0:05:00
    platform: state
    to: not_home
  condition: []
  action:
  - data_template:
      message: '''{{ trigger.to_state.state }}''

        '
      title: Device {{ trigger.to_state.name }} is
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578062059785'
  alias: '[System] Monitor Status'
  description: ''
  trigger:
  - entity_id:
    - sensor.monitor_dining_room
    - sensor.monitor_living_room
    for:
      minutes: 5
    platform: state
    to: offline
  condition: []
  action:
  - data:
      data_template:
        message: '''{{ trigger.to_state.state }}''

          '
        title: '{{ trigger.to_state.name }} is'
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578062752026'
  alias: '[System] Hass Started'
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      topic: monitor/scan/arrive
    service: mqtt.publish
  - data:
      message: '@here Home Assistant Online'
      target:
      - '510402538898718728'
    service: notify.hass_discord
  - data:
      name: nest
    service: frontend.set_theme
  - data:
      addon: c6a2317c_netdaemon
    service: hassio.addon_restart
- id: '1578062963561'
  alias: '[System] Z-wave Ready'
  description: ''
  trigger:
  - event_data: {}
    event_type: zwave.network_ready
    platform: event
  condition: []
  action:
  - data:
      message: Z-wave network ready
      target:
      - '510402538898718728'
    service: notify.hass_discord
- id: '1578063417620'
  alias: '[System] Hass Stopped'
  description: ''
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: '@here Home Assistant Offline'
      target:
      - '510402538898718728'
    service: notify.hass_discord
- id: '1578063765052'
  alias: '[System] Hass New Device Tracked'
  description: ''
  trigger:
  - event_data: {}
    event_type: device_tracker_new_device
    platform: event
  condition: []
  action:
  - data_template:
      message: 'New Device Tracked: {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})

        '
      target:
      - '510402538898718728'
    service: notify.hass_discord
- id: '1578063986693'
  alias: '[System] Hass New Platform Discovered'
  description: ''
  trigger:
  - event_data: {}
    event_type: PLATFORM_DISCOVERED
    platform: event
  condition: []
  action:
  - data_template:
      message: 'New Platform Discovered: {{trigger.event.data.service}} ({{trigger.event.data.discovered}})'
      target:
      - '510402538898718728'
    service: notify.hass_discord
- id: '1578064209397'
  alias: '[System] Hass Updater'
  description: ''
  trigger:
  - entity_id: sensor.version_available
    platform: state
  condition:
  - condition: template
    value_template: "{{\n  states('sensor.version_available')\n  !=\n  states('sensor.version_current')\n\
      }}"
  action:
  - data_template:
      message: Hass.io version {{ states('sensor.version_available') }} is now available!
      title: Upgrade time!
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578064427379'
  alias: '[System] Ip Ban Notify'
  description: ''
  trigger:
  - entity_id: persistent_notification.ipban
    platform: state
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != off }}'
  action:
  - data_template:
      message: '@here {{ trigger.state.attributes.message }}. Ip address has been
        banned.'
      title: Upgrade time!
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578064572241'
  alias: '[Cats] Litterbox All Counter Reset At Midnight'
  description: ''
  trigger:
  - at: '23:59:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: counter.all_litterbox_visits_today
    service: counter.reset
- id: '1578065031464'
  alias: '[House] Cleaning Mode'
  description: ''
  trigger:
  - entity_id: sensor.unlocked_by
    platform: state
    to: '''Cleaners'''
  condition:
  - condition: state
    entity_id: calendar.cleaning_day
    state: 'on'
  action:
  - entity_id: script.cleaning_time
    service: script.turn_on
  - entity_id: input_boolean.ec_lights_on_ring_control
    service: input_boolean.turn_on
  - data: {}
    entity_id: input_boolean.ad_litterboxes
    service: input_boolean.turn_off
  - data:
      message: Cleaners have arrived
      title: Cleaning time
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578065709121'
  alias: '[House] Cleaning Mode Off'
  description: ''
  trigger:
  - entity_id: calendar.house_cleaning
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: frontsensor.house_motion
    for:
      minutes: 10
    state: 'off'
  action:
  - entity_id: input_boolean.ec_lights_on_ring_control
    service: input_boolean.turn_off
  - entity_id: input_boolean.ad_litterboxes
    service: input_boolean.turn_on
  - data:
      message: ''
      title: Cleaning time over
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578066403796'
  alias: '[House] Guest Mode On'
  description: ''
  trigger:
  - entity_id: input_boolean.guest_mode
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: input_boolean.ec_lights_on_ring_control
    service: input_boolean.turn_on
  - data:
      message: Some automations turned off
      title: Guest mode on
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578066455390'
  alias: '[House] Guest Mode Off'
  description: ''
  trigger:
  - entity_id: input_boolean.guest_mode
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: input_boolean.ec_lights_on_ring_control
    service: input_boolean.turn_on
  - data:
      message: Automations turned on again
      title: Guest mode turned off
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578138454661'
  alias: '[Lights] Notification on window open and lights on'
  description: ''
  trigger:
  - entity_id: binary_sensor.bedroom_window
    for: 0:10:00
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: or
      conditions:
      - condition: state
        entity_id: light.bedroom_ceiling_light
        state: 'on'
      - condition: state
        entity_id: light.bedside_lamp
        state: 'on'
  action:
  - data:
      data:
        push:
          badge: 0
          category: lights_off_bedroom
      message: Do you want to turn off lights?
      title: Bedroom window open
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578147075758'
  alias: '[Lights] Lights off when bedroom window open'
  description: ''
  trigger:
  - event_data:
      actionName: LIGHTS_OFF_BEDROOM
    event_type: ios.notification_action_fired
    platform: event
  condition: []
  action:
  - entity_id: light.bedroom_ceiling_light
    service: light.turn_off
- id: '1578147522103'
  alias: '[Climate] Notification on high temp in bedroom'
  description: ''
  trigger:
  - above: '26'
    entity_id: sensor.bedroom_temperature
    platform: numeric_state
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.isa
      state: Home
    - condition: state
      entity_id: binary_sensor.bedroom_window
      state: 'off'
  action:
  - data:
      message: Open the window!
      title: Bedroom temp high
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578147585636'
  alias: '[Climate] Notification on low temp in bedroom'
  description: ''
  trigger:
  - below: '21'
    entity_id: sensor.bedroom_temperature
    platform: numeric_state
  condition:
  - condition: state
    entity_id: person.isa
    state: Home
  action:
  - data:
      message: Turn up the radiator or shut the window!
      title: Bedroom temperature low
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1578785601832'
  alias: '[Cats] [Moved to ad] Send image to Discord'
  description: ''
  trigger:
  - entity_id: binary_sensor.upstairs_litterbox_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: calendar.house_cleaning
    state: 'off'
  action:
  - delay: 00:00:20
  - data:
      data:
        images:
        - /config/www/motion/camera.isas_room_latest.jpg
      message: Cat on litterbox!
      target:
      - '665694350373683210'
    service: notify.hass_discord
- id: '1579009344959'
  alias: '[System] Hass New Entity registered'
  description: ''
  trigger:
  - event_data: {}
    event_type: entity_registry_updated
    platform: event
  condition: []
  action:
  - data_template:
      message: 'Entity {{trigger.event.data.action}}: {{trigger.event.data.entity_id}}
        - {{trigger.event.data.changes}}'
      target:
      - '510402538898718728'
    service: notify.hass_discord
- id: '1587306129134'
  alias: '[Blinds] Living Room Roller Blinds Up'
  description: ''
  trigger:
  - device_id: 4c1092ae02584579be29ec2399016071
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_short_press
  - device_id: 4c1092ae02584579be29ec2399016071
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_long_press
  condition: []
  action:
  - device_id: 82c20a4a058846fc8ecb7837d9c9370e
    domain: cover
    entity_id: cover.living_room_roller_blind_switch
    type: open
- id: '1587306204729'
  alias: '[Blinds] Living Room Roller Blinds 30%'
  description: ''
  trigger:
  - device_id: 4c1092ae02584579be29ec2399016071
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - data:
      position: 30
    entity_id: cover.living_room_roller_blind_level
    service: cover.set_cover_position
- id: '1587328171004'
  alias: '[Blinds] Living Room Roller Blind Stop on Release'
  description: ''
  trigger:
  - device_id: 4c1092ae02584579be29ec2399016071
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_long_release
  - device_id: 4c1092ae02584579be29ec2399016071
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  condition: []
  action:
  - entity_id: cover.living_room_roller_blind_level
    service: cover.stop_cover
- id: '1587364682944'
  alias: '[Blinds] Living Room Roller Blind Down at 06'
  description: ''
  trigger:
  - at: 06:00:00
    platform: time
  condition: []
  action:
  - data:
      position: 30
    entity_id: cover.living_room_roller_blind_level
    service: cover.set_cover_position
- id: '1587364801927'
  alias: '[Blinds] Living Room Roller Blind Up at 10'
  description: ''
  trigger:
  - at: '10:00:00'
    platform: time
  condition:
  - condition: device
    device_id: 90353caccb994684b823872fea8d9372
    domain: media_player
    entity_id: media_player.living_room_tv
    type: is_off
  action:
  - device_id: 82c20a4a058846fc8ecb7837d9c9370e
    domain: cover
    entity_id: cover.living_room_roller_blind_switch
    type: open
- id: '1587559387737'
  alias: '[Climate] Fan switch'
  description: ''
  trigger:
  - device_id: 4f74a8ce5e85483a94fad78aef51e4e3
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: light.globe
    service: homeassistant.toggle
- id: '1587621677067'
  alias: '[Blinds] Living Room Roller Blind Down'
  description: ''
  trigger:
  - device_id: 4c1092ae02584579be29ec2399016071
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_long_press
  condition: []
  action:
  - device_id: 82c20a4a058846fc8ecb7837d9c9370e
    domain: cover
    entity_id: cover.living_room_roller_blind_switch
    type: close
- id: '1587641472613'
  alias: '[House] Notify on low water level'
  description: ''
  trigger:
  - device_id: 6078752e73b94eee8a3e502d68970626
    domain: binary_sensor
    entity_id: binary_sensor.ikea_hydro_water_level
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: problem
  condition: []
  action:
  - data:
      message: Fill it up!
      title: Ikea hydro needs more water
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1589486639195'
  alias: '[Cats] Downstairs Litterbox Auto Light'
  description: ''
  trigger:
  - device_id: f48e6f61695146118277326f1ff9ab14
    domain: binary_sensor
    entity_id: binary_sensor.downstairs_litterbox_motion
    platform: device
    type: motion
  condition:
  - condition: device
    device_id: 50c6f2fe5bbb4be0819c56db497f8a92
    domain: light
    entity_id: light.downstairs_litterbox_light_strip
    type: is_off
  action:
  - brightness_pct: 15
    device_id: 50c6f2fe5bbb4be0819c56db497f8a92
    domain: light
    entity_id: light.downstairs_litterbox_light_strip
    type: turn_on
  - delay: 00:03:00
  - device_id: 50c6f2fe5bbb4be0819c56db497f8a92
    domain: light
    entity_id: light.downstairs_litterbox_light_strip
    type: turn_off
- id: '1589789239123'
  alias: '[Security] Ring Doorbell Low Battery'
  description: ''
  trigger:
  - below: '15'
    entity_id: sensor.ring_doorbell_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Low battery
      title: Ring Doorbell
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1589789734091'
  alias: '[Security] Ring Doorbell Flash Lights'
  description: Flash Upstairs Hallway and Yard lights on ding
  trigger:
  - device_id: 6c649502c14445c88f5e514065c5ad66
    domain: binary_sensor
    entity_id: binary_sensor.ring_doorbell_ding
    platform: device
    type: occupied
  condition: []
  action:
  - data: {}
    service: python_script.flash_lights_upstairs_hallway_and_yard
- id: '1589790297805'
  alias: '[Security] Smoke Alarm'
  description: ''
  trigger:
  - entity_id: binary_sensor.dining_room_smoke_alarm
    platform: state
    to: 'on'
  - entity_id: binary_sensor.upstairs_hallway_smoke_alarm
    platform: state
    to: 'on'
  - entity_id: binary_sensor.walk_in_closet_smoke_alarm
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      message: 'Passage: {{states.sensor.passage_temperature.state_with_unit}} Bathroom:
        {{states.sensor.downstairs_bathroom_temperature.state}} Stefan: {{states.sensor.stefan_temperature.state}}
        Bedroom: {{states.sensor.bedroom_temperature.state}}

        '
      title: '{{ trigger.to_state.name }} triggered'
    service: notify.mobile_app_isabella_s_iphone_x
- id: '1589790536204'
  alias: '[Climate] High Temperatures'
  description: ''
  trigger:
  - above: '35'
    entity_id: sensor.passage_temperature, sensor.downstairs_bathroom_temperature,
      sensor.stefan_temperature, sensor.bedroom_temperature
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: '{{ trigger.to_state.state }}'
      title: '{{ trigger.to_state.name }}'
    service: notify.mobile_app_isabella_s_iphone_x
