homeassistant:
  name: Home
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  # customize_glob: !include customglob.yaml
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        # - !secret trusted_network_1
        - !secret trusted_network_2
        - !secret trusted_network_3
        - !secret trusted_network_4
        - !secret trusted_network_5
    - type: legacy_api_password
      api_password: !secret http_password
      
  whitelist_external_dirs:
    - !secret motion_dir
    - !secret recording_dir

config:
hassio:
system_health:
ssdp:
zeroconf:
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # ip_ban_enabled: true
  # login_attempts_threshold: 3

updater:
discovery:
  ignore:
    - igd

# ########################################
# ###           ASSISTANTS             ###
# ########################################
# cloud: # !include assistants/cloud.yaml
homekit: !include assistants/homekit.yaml

# ########################################
# ###             MOBILE               ###
# ########################################
ios: !include notify/ios_config.yaml
mobile_app:

# ########################################
# ###                GUI               ###
# ########################################

# lovelace_gen:

lovelace:
  mode: yaml
  resources: !include_dir_merge_list lovelace/resources 
  dashboards:
    lovelace-dashboard:
      mode: yaml
      filename: ui-dashboard.yaml
      title: Dashboard
      icon: mdi:monitor-dashboard
      show_in_sidebar: true
      require_admin: false
    dwains-theme:
      mode: yaml
      title: Dwains Theme
      icon: mdi:alpha-d-box
      show_in_sidebar: true
      filename: dwains-theme-lovelace.yaml

map:

frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/hass-bha-icons.html
    - /local/dwains-theme/fonts/fontawesome/hass-fontawesome-solid.html
    - /local/dwains-theme/fonts/fontawesome/hass-fontawesome-regular.html
    # - /local/dwains-theme/fonts/fontawesome/hass-fontawesome-light.html #If have Font Awesome Light uncomment this line

netdaemon:
  
browser_mod:
  devices:
    24d2e744-aee3dfdb:
      name: Isa laptop
      disable:
        - light
        - media_player
        - sensor
    82ce1407-06ba38e8:
      name: Dashboard
      disable:
        - light
        - media_player
        - sensor
    49b3d945-27efcb05:
      name: Isa PC
      disable:
        - light
        - media_player
        - sensor
  disable:
    - all
      
# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

# ########################################
# ###              ENTITIES             ###
# ########################################
person:
media_player: !include entities/media_player.yaml
device_tracker: !include entities/device_tracker.yaml
zone:
  - name: 'Gun'
    latitude: !secret isama_lat
    longitude: !secret isama_long
    icon: mdi:map-marker
    radius: 100
alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include automations.yaml

# ########################################
# ###             SERVICES             ###
# ########################################
sun:
notify: !include notify/notify.yaml

python_script:
 
tts:
  - platform: google_translate

ffmpeg:
