# ## Automations regarding this have moved to Appdaemon

counter:
  litterbox_upstairs_visits:
    name: Upstairs Litterbox Visits
    step: 1
  litterbox_downstairs_visits:
    name: Downstairs Litterbox Visits
    step: 1
  all_litterbox_visits_today:
    name: All Litterbox Visits Today
    step: 1

input_number:
  upstairs_litterbox_persistence:
    name: Upstairs litterbox persistence
    min: 0
    max: 50
    step: 1
    mode: box

  downstairs_litterbox_persistence:
    name: Downstairs litterbox persistence
    min: 0
    max: 50
    step: 1
    mode: box

  all_litterbox_persistence:
    name: All litterbox persistence
    min: 0
    max: 50
    step: 1
    mode: box

input_select:
  ulitterbox_state:
    name: Upstairs Litterbox State
    options:
      - Clean
      - Dirty
      - Cleaning
    icon: mdi:paw
    
  dlitterbox_state:
    name: Downstairs Litterbox State
    options:
      - Clean
      - Dirty
      - Cleaning
    icon: mdi:paw
sensor:
  - platform: template
    sensors:
      upstairs_litterbox_visits:
        friendly_name: "Upstairs Litterbox Visits"
        unit_of_measurement: 'visit(s)'
        value_template: "{{ states('counter.litterbox_upstairs_visits') }}"
      downstairs_litterbox_visits:
        friendly_name: "Downstairs Litterbox Visits"
        unit_of_measurement: 'visit(s)'
        value_template: "{{ states('counter.litterbox_downstairs_visits') }}"
camera:
  - platform: mjpeg
    mjpeg_url: !secret upstairs_litterbox_url
    name: Upstairs Litterbox
    username: !secret upstairs_litterbox_username
    password: !secret upstairs_litterbox_password
    verify_ssl: false