# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/house_information.html

house_information:
  favorites:
    - entity: sensor.house_motion
    - entity: sensor.outer_doors
    - entity: sensor.outer_windows
    # - entity: sensor.front_door
    # - entity: sensor.back_door
    # - entity: sensor.yard_door
    # - entity: sensor.balcony_door
    # - entity: sensor.dining_room_window
    # - entity: sensor.bedroom_window
    # - entity: sensor.bedroom_door
    # - entity: sensor.isas_room_window
    #       #   name: Isas
    # - entity: binary_sensor.living_room_axis_motion_0
    #       #   name: Living Room Left
    #       #   secondary_info: last-changed
    # - entity: binary_sensor.passage_axis_motion_0
    #       #   name: Living Room Right
    #       #   secondary_info: last-changed
    # - entity: binary_sensor.passage_motion_sensor
    # - entity: binary_sensor.upstairs_hallway_motion_sensor
    #       #   name: Stairs
    # - entity: binary_sensor.stefans_room_motion
    #       #   name: Stefans Office
    # # - entity: switch.bike_charger
    #       #   name: E-bike charger
    #       #   include_history: true
    # - entity: binary_sensor.kitchen_motion
    #       #   name: Kitchen Cats
    # - entity: binary_sensor.downstairs_litterbox_motion
    # - entity: binary_sensor.upstairs_litterbox_motion
    # - entity: binary_sensor.hallway_motion
    #       #   name: Hallway
    # - entity: input_select.dryer_status
    #       #   name: Dryer
    #       #   icon: mdi:tumble-dryer
    #       #   include_history: true
    # - entity: input_select.washing_machine_status
    #       #   name: Washer
    #       #   icon: mdi:washing-machine
    #       #   include_history: true
  calendar:
    - calendar.isabella_alstrom
    - calendar.house