# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

more_page:
  addons:
    - name: Coronavirus
      icon: fas:disease
      path: 'dwains-theme/addons/more_page/coronavirus/page.yaml'