# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/persons.html

persons: 
  - name: Isa
    track: person.isa
    # picture_path: 'lovelace_ui/home/isa_square.jpg'
    show_map: true
    # more_entities:
    #   columns: 1 #optional
    #   entities:
    #     - entity: sensor.steps
    #     - entity: sensor.steps
    page_entities:
      columns: 1 #optional
      entities:
        - entity: device_tracker.isa_addon_presence
        - entity: proximity.home_isa
        - entity: device_tracker.isabella_s_iphone_x
        - entity: sensor.isa_battery_level
        - entity: sensor.isa_battery_state
        - entity: sensor.isa_geocoded_location
        - entity: device_tracker.isabellas_iphone_x_wifi
        - entity: sensor.isa_ssid
        - entity: sensor.dining_room_isabellas_iphone_x_bt
        - entity: sensor.living_room_isabellas_iphone_x_bt

        - entity: sensor.isa_average_active_pace
        - entity: sensor.isa_steps

  - name: Stefan
    track: person.stefan
    # picture_path: 'lovelace_ui/home/isa_square.jpg'
    show_map: true