# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/scenes.html

scenes:
  - entity: scene.movie_time
    icon: mdi:movie-open-outline
    icon_color: '#ffffff'
    background: 'linear-gradient( 135deg, #08f26e 10%, #059142 100%)'
  - entity: scene.morning_lights
    icon: mdi:weather-sunset-up
    icon_color: '#ffffff'
    background: 'linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)'
  - entity: script.goodnight
    icon: mdi:weather-night
    icon_color: '#ffffff'
    background: 'linear-gradient( 135deg, #6d4f73 10%, #301934 100%)'
  # - entity: light.downstairs_lights