binary_sensor:
  - platform: template
    sensors:
      ring_low_battery:
        friendly_name: 'Ring Doorbell Low Battery'
        entity_id: "sensor.ring_doorbell_battery"
        device_class: battery
        value_template: "{{ states('sensor.ring_doorbell_battery')|float < 20 }}"
