sensor:
  - platform: template
    sensors:
      house_motion:
        friendly_name: 'House Motion'
        entity_id:
          - binary_sensor.passage_motion_sensor
          - binary_sensor.upstairs_hallway_motion_sensor
          - binary_sensor.stefans_room_motion
          - binary_sensor.living_room_axis_motion_0
          - binary_sensor.passage_axis_motion_0
          - binary_sensor.hallway_motion
        value_template: >-
          {% if is_state('binary_sensor.passage_motion_sensor', 'on')
          or is_state("binary_sensor.upstairs_hallway_motion_sensor", "on")
          or is_state("binary_sensor.stefans_room_motion", "on")
          or is_state("binary_sensor.living_room_axis_motion_0", "on")
          or is_state("binary_sensor.passage_axis_motion_0", "on")
          or is_state("binary_sensor.hallway_motion", "on") %}
            Detected
          {% else %}
            No movement
          {% endif %}