sensor:
  - platform: template  
    sensors:
      dining_room_window:
        friendly_name: 'Dining area window'
        entity_id: "binary_sensor.dining_room_window"
        value_template: '{% if is_state("binary_sensor.dining_room_window", "on") %}Open{% elif is_state("binary_sensor.dining_room_window", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.dining_room_window", "on") %}mdi:window-open{% elif is_state("binary_sensor.dining_room_window", "off")%}mdi:window-closed{% else %}mdi:comment-question-outline{% endif %}'
      bedroom_window:
        friendly_name: 'Bedroom window'
        entity_id: "binary_sensor.bedroom_window"
        value_template: '{% if is_state("binary_sensor.bedroom_window", "on") %}Open{% elif is_state("binary_sensor.bedroom_window", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.bedroom_window", "on") %}mdi:window-open{% elif is_state("binary_sensor.bedroom_window", "off")%}mdi:window-closed{% else %}mdi:comment-question-outline{% endif %}'
      isas_room_window:
        friendly_name: 'Isas Room window'
        entity_id: "binary_sensor.isas_room_window"
        value_template: '{% if is_state("binary_sensor.isas_room_window", "on") %}Open{% elif is_state("binary_sensor.isas_room_window", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.isas_room_window", "on") %}mdi:window-open{% elif is_state("binary_sensor.isas_room_window", "off")%}mdi:window-closed{% else %}mdi:comment-question-outline{% endif %}'


      outer_windows:
        friendly_name: 'Outer Windows'
        entity_id: binary_sensor.bedroom_window, binary_sensor.dining_room_window
        value_template: >-
          {% if is_state("binary_sensor.dining_room_window", "on") %}
            Dining room
          {% elif is_state("binary_sensor.bedroom_window", "on") %}
            Bedroom          
          {% elif is_state("binary_sensor.isas_room_window", "on") %}
            Isas room
          {% else %}
            Closed
          {% endif %}

alert:
  dining_room_window_open:
    name: Dining area window left open
    done_message: Window closed
    entity_id: binary_sensor.dining_room_window
    state: 'on'
    repeat: 15
    can_acknowledge: True
    skip_first: True
    notifiers:
      - mobile_app_isabella_s_iphone_x