
homeassistant:
  customize:     
    sensor.trash:
      icon: mdi:delete
    sensor.dining_room_stefan_iphone_11_bt:
      source_type: bluetooth
    sensor.dining_room_isabellas_iphone_x_bt:
      source_type: bluetooth
    sensor.living_room_isabellas_iphone_x_bt:
      source_type: bluetooth
    sensor.living_room_stefan_iphone_11_bt:
      source_type: bluetooth

sensor:
  - platform: mqtt
    state_topic: 'monitor/dining_room/isa'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes_topic: 'monitor/dining_room/isa'
    name: dining_room_isabellas_iphone_x_bt
 
  - platform: mqtt
    state_topic: 'monitor/living_room/isa'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes_topic: 'monitor/living_room/isa'
    name: living_room_isabellas_iphone_x_bt

  - platform: mqtt
    state_topic: 'monitor/dining_room/stefan'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes_topic: 'monitor/dining_room/stefan'
    name: dining_room_stefan_iphone_11_bt

  - platform: mqtt
    state_topic: 'monitor/living_room/stefan'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes_topic: 'monitor/living_room/stefan'
    name: living_room_stefan_iphone_11_bt

  - platform: mqtt
    state_topic: 'monitor/dining_room/trash'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      Home
     {% else %}
      Away
     {% endif %}
    json_attributes_topic: 'monitor/dining_room/trash'
    name: Trash

  - platform: mqtt
    state_topic: 'monitor/dining_room/status'
    name: Monitor Dining Room

  - platform: mqtt
    state_topic: 'monitor/living_room/status'
    name: Monitor Living Room

proximity:
  home_isa: 
    zone: home
    devices:
      - device_tracker.isabella_s_iphone_x
    tolerance: 50
    unit_of_measurement: km
  home_stefan: 
    zone: home
    devices:
      - device_tracker.igrims_3
    tolerance: 50
    unit_of_measurement: km

automation:
  - alias: '[Presence] Presence MQTT event'
    initial_state: 'on'
    trigger:
    - platform: mqtt
      topic: 'monitor/home/#'
    action:
      event: HASS_MQTT_PRESENCE
      event_data_template:
        topic: '{{ trigger.topic }}'
        payload: '{{ trigger.payload }}'

  - alias: '[Presence] Presence Homebound'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: proximity.home_isa
        below: 6
      - platform: numeric_state
        entity_id: proximity.home_stefan
        below: 6
    condition:
      condition: or
      conditions:
      - condition: template
        value_template: '{{ states.proximity.home_stefan.attributes.dir_of_travel == "towards" }}'
      - condition: template
        value_template: '{{ states.proximity.home_isa.attributes.dir_of_travel == "towards" }}'
    action:
      - service: notify.mobile_app_isabella_s_iphone_x
        data_template:
          title: "{{ trigger.to_state.name | title }}"
          message: "{{ trigger.to_state.state }}"

